blank_issues_enabled: false
contact_links:
  - name: apexcharts-card Community Support
    url: https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877
    about: Please ask and answer usage questions here.
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: For general Home Assistant questions.
